import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

// Load fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        style={{ margin: 0 }}
      >
        <nav
          style={{
            background: '#f1f1f1',
            padding: '1rem',
            textAlign: 'center',
          }}
        >
          <a
            href="/"
            style={{
              marginRight: '1rem',
              color: '#0075ff',
              textDecoration: 'none',
            }}
          >
            Home
          </a>
          <a
            href="/services"
            style={{ color: '#0075ff', textDecoration: 'none' }}
          >
            Services
          </a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}

